import "./rain.css";
import "./sunRain.css";

const Rain = ({isDaytime}) => {

    // If it's daytime, use "sunRain" class
    // If it's not daytime, use "rain" class
    const rainClass = isDaytime ? 'sunRain' : 'rain'

    return (
        <div>
            {/* Just a ton of rain icons. The CSS randomizes their details. */}
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
            <i class={rainClass}></i>
        </div>
    );
};

export default Rain;
